import { containerContents, containersAtCurrentLocation, currentLocation, formatClock, getContainerActions, getContextActions, getItemActions, inventoryItems, looseItemsAtCurrentLocation, performAction, type ActionOption, type ActionResult, type GameAction, type GameState } from '../engine';
import { describeCurrentLocation } from '../narrative/location';

export type ViewId = 'home' | 'map' | 'inventory' | 'phone';
interface UiState { view: ViewId; popupTarget: { kind: 'item' | 'container'; id: string } | undefined; result: ActionResult | undefined; }
interface MountOptions { persist(state: GameState): void; }
const statMeta = [['healthPv','❤️','Santé','Points de vie. À 0 PV, le personnage meurt.'],['hunger','🍽️','Faim','Plus le pourcentage monte, plus la faim devient critique.'],['thirst','💧','Soif','0 % = aucune soif ; 100 % = situation critique.'],['fatigue','💤','Fatigue','Représente le besoin de repos et de sommeil.'],['stress','🧠','Stress','Le stress peut perturber certaines décisions et actions.'],['pain','🩹','Douleur','La douleur reflète blessures et inconfort physique.']] as const;
function escapeHtml(value:string):string{return value.replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]??c));}
function statValue(state:GameState,key:(typeof statMeta)[number][0]):string{return key==='healthPv'?`${Math.round(state.player.healthPv)} PV`:`${Math.round(state.player.needs[key])} %`;}
function hud(state:GameState):string{const location=currentLocation(state);return `<header class="hud" data-testid="hud"><div class="hud-top"><div><div class="clock">${formatClock(state)}</div><div class="place">${escapeHtml(location.name)}</div></div><button class="close" type="button" data-menu aria-label="Menu">☰</button></div><div class="stats">${statMeta.map(([key,icon,label,description])=>`<button class="stat" type="button" data-stat="${key}" data-stat-label="${label}" data-stat-description="${description}"><span class="icon">${icon}</span><span class="value">${statValue(state,key)}</span></button>`).join('')}</div></header>`;}
function actionButton(action:ActionOption):string{return `<button class="action" type="button" data-action="${action.id}"${action.targetId?` data-target="${escapeHtml(action.targetId)}"`:''}${action.sourceId?` data-source="${escapeHtml(action.sourceId)}"`:''}${action.amountMl!==undefined?` data-amount="${action.amountMl}"`:''}${action.seconds!==undefined?` data-seconds="${action.seconds}"`:''}><div class="row-main"><div class="row-title">${escapeHtml(action.label)}</div>${action.detail?`<div class="row-sub">${escapeHtml(action.detail)}</div>`:''}</div><div class="chev">›</div></button>`;}
function objectRow(kind:'item'|'container',id:string,icon:string,title:string,sub:string):string{return `<button class="row" type="button" data-open-${kind}="${escapeHtml(id)}"><div class="row-icon">${icon}</div><div class="row-main"><div class="row-title">${escapeHtml(title)}</div><div class="row-sub">${escapeHtml(sub)}</div></div><div class="chev">›</div></button>`;}
function resultCard(result:ActionResult|undefined):string{return result?`<div class="card result"><div class="result-title">${escapeHtml(result.title)}</div><div class="result-body">${escapeHtml(result.body)}</div></div>`:'';}
function homeView(state:GameState,ui:UiState):string{const location=currentLocation(state),loose=looseItemsAtCurrentLocation(state),containers=containersAtCurrentLocation(state),actions=getContextActions(state);return `<main data-testid="home-view"><section class="card hero"><div class="eyebrow">Situation</div><h1>${escapeHtml(location.name)}</h1><div class="copy">${escapeHtml(describeCurrentLocation(state))}</div></section>${resultCard(ui.result)}<div class="section-title">Objets et contenants présents</div>${containers.map(c=>objectRow('container',c.id,'🗄️',c.name,c.open?'Ouvert':c.locked?'Verrouillé':'Fermé')).join('')}${loose.map(i=>objectRow('item',i.id,'📦',i.name,'Objet à portée de main')).join('')}${containers.length===0&&loose.length===0?'<div class="empty">Aucun objet visible ici.</div>':''}<div class="section-title">Actions</div>${actions.map(actionButton).join('')}</main>`;}
function inventoryView(state:GameState,ui:UiState):string{const items=inventoryItems(state);return `<main data-testid="inventory-view"><section class="card"><div class="eyebrow">Inventaire</div><h1>Objets transportés</h1><div class="copy">Les actions liées aux objets sont accessibles uniquement en touchant l’objet.</div></section>${resultCard(ui.result)}${items.length?items.map(i=>objectRow('item',i.id,'🎒',i.name,i.examined?'Examiné':'Non examiné')).join(''):'<div class="empty">Inventaire vide.</div>'}</main>`;}
function phoneView(state:GameState):string{const mobile=state.infrastructure.mobile,phone=state.items.phone_01;return `<main data-testid="phone-view"><section class="card"><div class="eyebrow">Téléphone</div><h1>Appareil</h1><div class="copy">Batterie : ${phone?.batteryPercent??'?'} %. Réseau : ${mobile.available?`${mobile.signal}/4`:'indisponible'}.</div></section><div class="dev-note">La messagerie sera reconnectée ici après validation de la parité moteur.</div></main>`;}
function mapView():string{return `<main data-testid="map-view"><section class="card"><div class="eyebrow">Carte</div><h1>Migration technique</h1><div class="copy">La carte Leaflet sera branchée comme adaptateur UI indépendant une fois le noyau moteur stabilisé.</div></section></main>`;}
function nav(view:ViewId):string{const entries:Array<[ViewId,string,string]>=[['home','🏠','Accueil'],['map','🗺️','Carte'],['inventory','🎒','Inventaire'],['phone','📱','Téléphone']];return `<nav>${entries.map(([id,icon,label])=>`<button type="button" class="nav${view===id?' active':''}" data-nav="${id}"><span>${icon}</span>${label}</button>`).join('')}</nav>`;}
function targetPopup(state:GameState,ui:UiState):string{const target=ui.popupTarget;if(!target)return'';if(target.kind==='container'){const c=state.containers[target.id];if(!c)return'';const actions=getContainerActions(state,c.id),contents=containerContents(state,c.id);return `<div class="overlay"><section class="sheet" role="dialog" aria-modal="true"><div class="sheet-head"><div><div class="sheet-title">${escapeHtml(c.name)}</div><div class="sheet-sub">${c.open?'Ouvert':c.locked?'Verrouillé':'Fermé'}</div></div><button type="button" class="close" data-close-popup>×</button></div>${actions.map(actionButton).join('')}${c.open?`<div class="section-title">Contenu</div>${contents.length?contents.map(i=>objectRow('item',i.id,'📦',i.name,'Dans le contenant')).join(''):'<div class="empty">Ce contenant est vide.</div>'}`:''}</section></div>`;}const item=state.items[target.id];if(!item)return'';const actions=getItemActions(state,item.id);const details=item.examined?[item.condition?`État : ${item.condition}`:'',item.capacityMl!==undefined?`Contenu : ${item.liquidMl??0}/${item.capacityMl} ml`:'',item.batteryPercent!==undefined?`Batterie : ${item.batteryPercent} %`:''].filter(Boolean).join(' · '):'Touchez « Examiner » pour obtenir davantage d’informations.';return `<div class="overlay"><section class="sheet" role="dialog" aria-modal="true"><div class="sheet-head"><div><div class="sheet-title">${escapeHtml(item.name)}</div><div class="sheet-sub">${escapeHtml(details)}</div></div><button type="button" class="close" data-close-popup>×</button></div>${actions.map(actionButton).join('')}</section></div>`;}
function menuPopup():string{return `<div class="overlay"><section class="sheet"><div class="sheet-head"><div><div class="sheet-title">Menu</div><div class="sheet-sub">v0.2.0-dev · refactor technique</div></div><button type="button" class="close" data-close-popup>×</button></div><div class="section-title">Architecture</div><div class="dev-note">Build standard ES modules. Aucun eval, aucun module gzip/base64. Le moteur ne dépend pas du DOM.</div></section></div>`;}

export function mountApp(root:HTMLElement,initialState:GameState,options:MountOptions):void{let state=initialState;let ui:UiState={view:'home',popupTarget:undefined,result:undefined};let menuOpen=false;const render=()=>{const body=ui.view==='home'?homeView(state,ui):ui.view==='inventory'?inventoryView(state,ui):ui.view==='phone'?phoneView(state):mapView();root.innerHTML=`${hud(state)}${body}${nav(ui.view)}${targetPopup(state,ui)}${menuOpen?menuPopup():''}`;};const execute=(action:GameAction)=>{const transition=performAction(state,action);state=transition.state;ui.result=transition.result;options.persist(state);render();};root.addEventListener('click',(event)=>{const target=event.target as HTMLElement;const button=target.closest<HTMLButtonElement>('button');if(!button)return;const navId=button.dataset.nav as ViewId|undefined;if(navId){ui={view:navId,popupTarget:undefined,result:ui.result};menuOpen=false;render();return;}if(button.dataset.menu!==undefined){menuOpen=true;render();return;}if(button.dataset.closePopup!==undefined){ui.popupTarget=undefined;menuOpen=false;render();return;}if(button.dataset.openItem){ui.popupTarget={kind:'item',id:button.dataset.openItem};render();return;}if(button.dataset.openContainer){ui.popupTarget={kind:'container',id:button.dataset.openContainer};render();return;}if(button.dataset.stat){root.querySelector('.stat-popover')?.remove();const rect=button.getBoundingClientRect(),popover=document.createElement('div');popover.className='stat-popover';popover.style.top=`${Math.min(window.innerHeight-120,rect.bottom+6)}px`;popover.style.left='12px';popover.innerHTML=`<strong>${escapeHtml(button.dataset.statLabel??'')}</strong><p>${escapeHtml(button.dataset.statDescription??'')}</p>`;document.body.append(popover);window.setTimeout(()=>popover.remove(),2600);return;}const actionId=button.dataset.action as GameAction['id']|undefined;if(actionId){const action:GameAction={id:actionId};if(button.dataset.target)action.targetId=button.dataset.target;if(button.dataset.source)action.sourceId=button.dataset.source;if(button.dataset.amount)action.amountMl=Number(button.dataset.amount);if(button.dataset.seconds)action.seconds=Number(button.dataset.seconds);execute(action);}});render();}
