import { describe, expect, it } from 'vitest';
import { getContainerActions, getContextActions, getItemActions, performAction } from '../../src/engine/actions';
import { describeItemExamination } from '../../src/engine/examination';
import { containerContents } from '../../src/engine/selectors';
import { createInitialState } from '../../src/engine/state';

describe('action authority', () => {
  it('keeps object actions out of the main context menu', () => { const state=createInitialState(); const ids=getContextActions(state).map(a=>a.id); expect(ids).not.toContain('TAKE_ITEM'); expect(ids).not.toContain('EXAMINE_ITEM'); expect(ids).not.toContain('FILL_LIQUID_CONTAINER'); });
  it('opens every container directly and reveals its content', () => { const state=createInitialState(); expect(containerContents(state,'bedroom_drawer')).toEqual([]); expect(getContainerActions(state,'bedroom_drawer').map(a=>a.id)).toEqual(['OPEN_CONTAINER']); const t=performAction(state,{id:'OPEN_CONTAINER',targetId:'bedroom_drawer'}); expect(t.result.success).toBe(true); expect(containerContents(t.state,'bedroom_drawer').map(i=>i.id)).toEqual(['spare_key_01']); });
  it('uses the same container interaction to close an already open container', () => { const state=createInitialState(); const opened=performAction(state,{id:'OPEN_CONTAINER',targetId:'bedroom_drawer'}); expect(opened.state.containers.bedroom_drawer?.open).toBe(true); const closed=performAction(opened.state,{id:'OPEN_CONTAINER',targetId:'bedroom_drawer'}); expect(closed.result.success).toBe(true); expect(closed.state.containers.bedroom_drawer?.open).toBe(false); expect(closed.result.title).toContain('refermez'); });
  it('never exposes a Search/Fouiller action for containers', () => { const state=createInitialState(); const all=getContainerActions(state,'bedroom_drawer'); expect(all.some(a=>/search|fouill/i.test(`${a.id} ${a.label}`))).toBe(false); });
  it('apple reduces hunger by 9 and thirst by 4 before time drift', () => { let state=createInitialState(); state=performAction(state,{id:'MOVE',targetId:'kitchen'}).state; state=performAction(state,{id:'TAKE_ITEM',targetId:'apple_01'}).state; const h=state.player.needs.hunger,t=state.player.needs.thirst; const r=performAction(state,{id:'EAT_ITEM',targetId:'apple_01'}); expect(r.result.success).toBe(true); expect(r.state.player.needs.hunger).toBeLessThan(h-8.8); expect(r.state.player.needs.thirst).toBeLessThan(t-3.8); expect(r.state.items.apple_01?.location.kind).toBe('consumed'); });
  it('offers and performs obvious food use directly from the room', () => { let state=createInitialState(); state=performAction(state,{id:'MOVE',targetId:'kitchen'}).state; expect(getItemActions(state,'apple_01').map(a=>a.id)).toEqual(expect.arrayContaining(['EAT_ITEM','TAKE_ITEM'])); const r=performAction(state,{id:'EAT_ITEM',targetId:'apple_01'}); expect(r.result.success).toBe(true); expect(r.state.items.apple_01?.location.kind).toBe('consumed'); expect(r.state.player.inventoryIds).not.toContain('apple_01'); });
  it('lets the player drink from a reachable bottle without inventory busywork', () => { let state=createInitialState(); state=performAction(state,{id:'MOVE',targetId:'kitchen'}).state; expect(getItemActions(state,'water_01').map(a=>a.id)).toEqual(expect.arrayContaining(['DRINK_ITEM','TAKE_ITEM'])); const r=performAction(state,{id:'DRINK_ITEM',targetId:'water_01',amountMl:250}); expect(r.result.success).toBe(true); expect(r.state.items.water_01?.liquidMl).toBe(250); expect(r.state.items.water_01?.location).toEqual({kind:'location',id:'kitchen'}); });
  it('shows bottle refill only in the bottle popup when carried and not full', () => { let state=createInitialState(); state=performAction(state,{id:'MOVE',targetId:'kitchen'}).state; state=performAction(state,{id:'TAKE_ITEM',targetId:'water_01'}).state; state=performAction(state,{id:'DRINK_ITEM',targetId:'water_01',amountMl:250}).state; expect(getContextActions(state).some(a=>a.id==='FILL_LIQUID_CONTAINER')).toBe(false); expect(getItemActions(state,'water_01').some(a=>a.id==='FILL_LIQUID_CONTAINER')).toBe(true); });
  it('Examiner reveals role, operation and live state without gating normal use', () => { const state=createInitialState(); expect(getItemActions(state,'phone_01').map(a=>a.id)).toEqual(expect.arrayContaining(['USE_ITEM','EXAMINE_ITEM'])); const r=performAction(state,{id:'EXAMINE_ITEM',targetId:'phone_01'}); expect(r.result.success).toBe(true); expect(r.state.items.phone_01?.examined).toBe(true); expect(r.result.body).toContain('téléphone personnel'); expect(r.result.body).toContain('fonctionne sur batterie'); expect(r.result.body).toContain('Batterie : 78.0 %'); expect(describeItemExamination(r.state,'phone_01')).toBe(r.result.body); });
  it('Examiner reports changing liquid state from the same canonical description', () => { let state=createInitialState(); state=performAction(state,{id:'MOVE',targetId:'kitchen'}).state; state=performAction(state,{id:'TAKE_ITEM',targetId:'water_01'}).state; state=performAction(state,{id:'DRINK_ITEM',targetId:'water_01',amountMl:250}).state; const r=performAction(state,{id:'EXAMINE_ITEM',targetId:'water_01'}); expect(r.result.body).toContain('contenant transportable'); expect(r.result.body).toContain('remplie à une source d’eau'); expect(r.result.body).toContain('Contenu actuel : 250/500 ml'); });
});
