import { createInitialPhoneState } from './phone';
import type { GameState } from '../engine/model';
import { GAME_VERSION, SAVE_SCHEMA_VERSION } from '../version';

export const INITIAL_STATE: GameState = {
  schemaVersion: SAVE_SCHEMA_VERSION,
  gameVersion: GAME_VERSION,
  clock: { day: 1, secondOfDay: 7 * 3600 + 12 * 60 },
  engine: {
    damageBudgetPv: 0,
    elapsedSeconds: 0,
    nextEffectId: 1,
    infrastructureSeed: 1701,
    infrastructureSimulationEnabled: true,
    worldEventSeed: 1801,
    worldEventSimulationEnabled: true,
  },
  player: {
    locationId: 'bedroom',
    healthPv: 100,
    needs: { hunger: 12, thirst: 10, fatigue: 18, stress: 22, pain: 0 },
    inventoryIds: ['phone_01'],
    alive: true,
  },
  locations: {
    bedroom: { id: 'bedroom', name: 'Chambre', ambientTemperatureC: 20, ambientHumidityPercent: 50, ventilation: 0.15, features: {}, position: { x: 0, y: 0 } },
    hallway: { id: 'hallway', name: 'Couloir', ambientTemperatureC: 20, ambientHumidityPercent: 50, ventilation: 0.12, features: {}, position: { x: 8, y: 0 } },
    girls_room: { id: 'girls_room', name: 'Chambre des filles', ambientTemperatureC: 20, ambientHumidityPercent: 50, ventilation: 0.14, features: {}, position: { x: 8, y: -10 } },
    bathroom: { id: 'bathroom', name: 'Salle de bain', ambientTemperatureC: 20, ambientHumidityPercent: 55, ventilation: 0.2, features: { tap: true, powerOutlet: true }, position: { x: 16, y: -10 } },
    living_room: { id: 'living_room', name: 'Salon', ambientTemperatureC: 20, ambientHumidityPercent: 50, ventilation: 0.18, features: { powerOutlet: true }, position: { x: 18, y: 0 } },
    kitchen: { id: 'kitchen', name: 'Cuisine', ambientTemperatureC: 20, ambientHumidityPercent: 50, ventilation: 0.18, features: { tap: true, powerOutlet: true }, position: { x: 30, y: 0 } },
    garage: { id: 'garage', name: 'Garage', ambientTemperatureC: 19, ambientHumidityPercent: 54, ventilation: 0.3, features: { powerOutlet: true }, position: { x: 30, y: 12 } },
    garden: { id: 'garden', name: 'Jardin', ambientTemperatureC: 20, ambientHumidityPercent: 50, ventilation: 1, features: {}, position: { x: 18, y: 14 } },
    driveway: { id: 'driveway', name: 'Allée devant la maison', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 34, y: 18 } },
    home_street: { id: 'home_street', name: 'Rue résidentielle', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 48, y: 18 } },
    neighbor_front: { id: 'neighbor_front', name: 'Maison voisine', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 48, y: 6 } },
    bus_stop: { id: 'bus_stop', name: 'Arrêt de bus', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 60, y: 18 } },
    small_park: { id: 'small_park', name: 'Petit parc', ambientTemperatureC: 20, ambientHumidityPercent: 52, ventilation: 1, features: {}, position: { x: 72, y: 18 } },
    crossroads: { id: 'crossroads', name: 'Carrefour', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 84, y: 18 } },
    pharmacy_front: { id: 'pharmacy_front', name: 'Devant la pharmacie', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 84, y: 6 } },
    grocery_front: { id: 'grocery_front', name: 'Devant la supérette', ambientTemperatureC: 20, ambientHumidityPercent: 51, ventilation: 1, features: {}, position: { x: 96, y: 18 } },
  },
  connections: {
    bedroom_kitchen: { id: 'bedroom_kitchen', a: 'bedroom', b: 'kitchen', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 12, hiddenFromContext: true },
    bedroom_hallway: { id: 'bedroom_hallway', a: 'bedroom', b: 'hallway', type: 'door', open: true, locked: false, openSeconds: 2, travelSeconds: 5 },
    hallway_girls_room: { id: 'hallway_girls_room', a: 'hallway', b: 'girls_room', type: 'door', open: true, locked: false, openSeconds: 2, travelSeconds: 4 },
    hallway_bathroom: { id: 'hallway_bathroom', a: 'hallway', b: 'bathroom', type: 'door', open: true, locked: false, openSeconds: 2, travelSeconds: 5 },
    hallway_living_room: { id: 'hallway_living_room', a: 'hallway', b: 'living_room', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 7 },
    living_room_kitchen: { id: 'living_room_kitchen', a: 'living_room', b: 'kitchen', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 6 },
    living_room_garden: { id: 'living_room_garden', a: 'living_room', b: 'garden', type: 'door', open: true, locked: false, openSeconds: 2, travelSeconds: 7 },
    kitchen_garden: { id: 'kitchen_garden', a: 'kitchen', b: 'garden', type: 'door', open: true, locked: false, openSeconds: 2, travelSeconds: 10, hiddenFromContext: true },
    kitchen_garage: { id: 'kitchen_garage', a: 'kitchen', b: 'garage', type: 'door', open: false, locked: false, openSeconds: 3, travelSeconds: 6 },
    garage_driveway: { id: 'garage_driveway', a: 'garage', b: 'driveway', type: 'door', open: false, locked: false, openSeconds: 5, travelSeconds: 6 },
    garden_driveway: { id: 'garden_driveway', a: 'garden', b: 'driveway', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 10 },
    driveway_home_street: { id: 'driveway_home_street', a: 'driveway', b: 'home_street', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 18 },
    home_street_neighbor_front: { id: 'home_street_neighbor_front', a: 'home_street', b: 'neighbor_front', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 35 },
    home_street_bus_stop: { id: 'home_street_bus_stop', a: 'home_street', b: 'bus_stop', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 55 },
    bus_stop_small_park: { id: 'bus_stop_small_park', a: 'bus_stop', b: 'small_park', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 65 },
    small_park_crossroads: { id: 'small_park_crossroads', a: 'small_park', b: 'crossroads', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 90 },
    crossroads_pharmacy_front: { id: 'crossroads_pharmacy_front', a: 'crossroads', b: 'pharmacy_front', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 45 },
    crossroads_grocery_front: { id: 'crossroads_grocery_front', a: 'crossroads', b: 'grocery_front', type: 'passage', open: true, locked: false, openSeconds: 0, travelSeconds: 65 },
  },
  containers: {
    bedroom_drawer: { id: 'bedroom_drawer', definitionId: 'drawer', name: 'Tiroir de la table de nuit', locationId: 'bedroom', open: false, locked: false, contentIds: ['spare_key_01'] },
    kitchen_fridge: { id: 'kitchen_fridge', definitionId: 'refrigerator', name: 'Réfrigérateur', locationId: 'kitchen', open: false, locked: false, contentIds: [] },
  },
  items: {
    phone_01: { id: 'phone_01', definitionId: 'smartphone', name: 'Téléphone', location: { kind: 'inventory' }, examined: false, batteryPercent: 78, condition: 'Bon état' },
    apple_01: { id: 'apple_01', definitionId: 'apple', name: 'Pomme', location: { kind: 'location', id: 'kitchen' }, examined: false, freshnessPercent: 94 },
    water_01: { id: 'water_01', definitionId: 'water_bottle', name: "Bouteille d’eau", location: { kind: 'location', id: 'kitchen' }, examined: false, liquidMl: 500, capacityMl: 500, condition: 'Bon état' },
    towel_01: { id: 'towel_01', definitionId: 'towel', name: 'Torchon', location: { kind: 'location', id: 'kitchen' }, examined: false, condition: 'Sec' },
    outlet_01: { id: 'outlet_01', definitionId: 'wall_outlet', name: 'Prise électrique', location: { kind: 'location', id: 'kitchen' }, examined: false },
    spare_key_01: { id: 'spare_key_01', definitionId: 'key', name: 'Petite clé', location: { kind: 'container', id: 'bedroom_drawer' }, examined: false, condition: 'Bon état' },
  },
  infrastructure: {
    water: { available: true, pressure: 1 },
    electricity: { available: true, voltagePercent: 100 },
    mobile: { available: true, signal: 4, signalPercent: 100 },
    transitions: [],
  },
  world: {
    effects: [],
    windowsOpen: { bedroom: false, kitchen: false },
    leakActive: false,
    scheduledEvents: [
      { id: 'evt_noise', atSeconds: 5 * 60, type: 'noise_source', locationId: 'kitchen', processed: false },
      { id: 'evt_leak', atSeconds: 12 * 60, type: 'water_leak', locationId: 'kitchen', processed: false },
      { id: 'evt_smoke', atSeconds: 25 * 60, type: 'smoke', locationId: 'garden', processed: false },
    ],
    eventHistory: [],
    eventSources: {},
    events: [],
  },
  phone: createInitialPhoneState(),
  memory: { shoutedForWife: false, visitedLocationIds: ['bedroom'] },
};
